# Generated by Django 6.0.3 on 2026-04-02 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('famouswomen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='famouswomen',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='famouswomen',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='famouswomen.category'),
        ),
        migrations.AddField(
            model_name='famouswomen',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='famouswomen.tagpost'),
        ),
    ]
